server:
  port: 8086

spring:
  application:
    name: zuul
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: feign
      sensitiveHeaders: "*"
    api-b:
      path: /api-b/**
      serviceId: feign1
      sensitiveHeaders: "*"
  host:
    socket-timeout-millis: 12000
    connect-timeout-millis: 12000
logging:
  level:
    com.netflix: debug
